const root=document.getElementById('adminApp');
const DEMO_FARMERS=[
 {id:'F001',name:'Ramesh Kumar',farm:'Green Valley FPO',location:'Lucknow',method:'FPO / assisted',status:'Verified',phone:'9876543210',joined:'18 Sep 2026',crops:'Tomatoes, Potatoes',documents:'FPO membership record, farming details'},
 {id:'F002',name:'Suresh Yadav',farm:'Kisan Pragati Farm',location:'Lucknow',method:'Authorized ID',status:'Verified',phone:'9876501234',joined:'17 Sep 2026',crops:'Potatoes',documents:'Authorized identity check, farm details'},
 {id:'F003',name:'Anita Verma',farm:'Shakti FPO',location:'Barabanki',method:'FPO / assisted',status:'Verified',phone:'9876512345',joined:'16 Sep 2026',crops:'Onions',documents:'FPO membership record, farm details'},
 {id:'F004',name:'Mohan Singh',farm:'Mohan Farms',location:'Lucknow',method:'Authorized ID',status:'Pending review',phone:'9876523456',joined:'25 Sep 2026',crops:'Green Chilies',documents:'Authorized identity check pending'}
];
function read(k,f){try{const v=localStorage.getItem(k);return v?JSON.parse(v):f}catch(e){return f}}
function write(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch(e){}}
function listings(){return read('kcListings',[])}
function orders(){return read('kcOrders',[])}
function farmersData(){const existing=read('kcFarmers',null);if(Array.isArray(existing)&&existing.length)return existing;write('kcFarmers',DEMO_FARMERS);return DEMO_FARMERS}
function disputes(){
  const existing=read('kcDisputes',null);
  if(Array.isArray(existing))return existing;
  const demo=[
    {id:'D1001',type:'Quality mismatch',severity:'High',status:'Open',order:'KC-481920',parties:'Ramesh Kumar ↔ Buyer #B104',reason:'Buyer reports tomatoes were softer than the listing freshness description.',created:'26 Sep 2026, 10:20',evidence:'Order details + buyer report',source:'Demo seed'},
    {id:'D1002',type:'Late / failed delivery',severity:'Medium',status:'Investigating',order:'KC-472611',parties:'Mohan Singh ↔ Buyer #B087',reason:'Delivery partner status has not changed after pickup window.',created:'25 Sep 2026, 17:40',evidence:'Tracking timeline',source:'Demo seed'},
    {id:'D1003',type:'Listing information issue',severity:'Low',status:'Monitoring',order:'No order',parties:'Anita Verma',reason:'Price/quantity listing was edited repeatedly in a short period.',created:'25 Sep 2026, 14:10',evidence:'Listing activity log',source:'Risk signal'}
  ];
  write('kcDisputes',demo);return demo;
}
function header(){return `<header class="top"><div class="brand">🌱 Kisan<span>Connect</span></div><div class="top-actions"><span class="admin-badge">ADMIN / OPERATIONS</span><button class="btn secondary" onclick="window.location.href='index.html'">← Main website</button></div></header>`}
function shell(content){root.innerHTML=header()+content}
function login(){root.innerHTML=`<main class="login"><section class="panel auth"><div style="font-size:34px">⚙️</div><span class="pill">KISANCONNECT ADMIN</span><h1>Operations Panel</h1><p class="muted">Manage farmers, listings, orders and marketplace operations from a separate admin portal.</p><form class="form" onsubmit="adminLogin(event)"><div class="field"><label>Username</label><input id="u" value="admin" required></div><div class="field"><label>Password</label><input id="pw" type="password" placeholder="Enter demo password" required></div><button class="btn primary">Sign in</button></form><p class="small muted">Prototype credentials: <b>admin</b> / <b>admin123</b></p><button class="btn secondary" onclick="window.location.href='index.html'">Open main website</button></section></main>`}
function adminLogin(e){e.preventDefault();if(document.getElementById('u').value==='admin'&&document.getElementById('pw').value==='admin123'){sessionStorage.setItem('kcAdmin','1');dashboard()}else alert('Demo login: admin / admin123')}
function nav(active){return `<div class="nav"><button class="btn secondary ${active==='overview'?'active':''}" onclick="dashboard()">Overview</button><button class="btn secondary ${active==='farmers'?'active':''}" onclick="farmers()">Farmers</button><button class="btn secondary ${active==='listings'?'active':''}" onclick="adminListings()">Listings</button><button class="btn secondary ${active==='orders'?'active':''}" onclick="adminOrders()">Orders & logistics</button><button class="btn secondary ${active==='recovery'?'active':''}" onclick="recovery()">Unsold stock</button><button class="btn secondary ${active==='risk'?'active':''}" onclick="riskDisputes()">⚠️ Risk & disputes</button></div>`}
function guard(){if(sessionStorage.getItem('kcAdmin')!=='1'){login();return false}return true}
function dashboard(){if(!guard())return;const ls=listings(),os=orders(),fs=farmersData(),slow=ls.filter(x=>x.status==='Slow sales').length; shell(`<main class="wrap">${nav('overview')}<div class="row between"><div><h1>Operations Overview</h1><p class="muted">Live prototype data shared with the farmer and buyer portals.</p></div><button class="btn secondary" onclick="location.reload()">↻ Refresh</button></div><div class="grid" style="margin-top:18px"><div class="card metric-card"><div class="small muted">Registered/demo farmers</div><div class="metric">${fs.length}</div></div><div class="card metric-card"><div class="small muted">Active listings</div><div class="metric">${ls.filter(x=>x.status==='Active').length}</div></div><div class="card metric-card"><div class="small muted">Orders</div><div class="metric">${os.length}</div></div><div class="card metric-card"><div class="small muted">Slow-sale listings</div><div class="metric">${slow}</div></div></div><div class="layout2"><section class="card"><h2>⚠️ Requires attention</h2><div class="statline"><span>Farmers pending review</span><b>${fs.filter(x=>x.status!=='Verified').length}</b></div><div class="statline"><span>Slow-sale listings</span><b>${slow}</b></div><div class="statline"><span>Orders in transit</span><b>${os.filter(x=>x.status==='In transit').length}</b></div><div class="statline"><span>Orders awaiting acceptance</span><b>${os.filter(x=>x.status==='Order placed').length}</b></div></section><section class="card"><h2>🔗 Shared marketplace</h2><p class="muted">Changes made here affect the same browser demo data used by the main website.</p><div class="notice small"><b>Example:</b> pausing/removing a listing creates a notification for the affected farmer. The buyer marketplace also hides non-active listings.</div><div style="height:12px"></div><button class="btn primary" onclick="adminListings()">Manage listings →</button></section></div><p class="footer-note">Prototype only. This admin login is not production authentication and all shared data is stored locally in this browser.</p></main>`)}
function farmers(){if(!guard())return;const fs=farmersData();shell(`<main class="wrap">${nav('farmers')}<div class="row between"><div><h1>Farmer Verification</h1><p class="muted">Review identity/farming verification status before granting marketplace access.</p></div></div><section class="card wide"><table class="table"><tr><th>Farmer</th><th>Farm / FPO</th><th>Location</th><th>Method</th><th>Status</th><th>Action</th></tr>${fs.map(f=>`<tr><td><b>${f.name}</b><div class="small muted">${f.phone||'—'}</div></td><td>${f.farm}</td><td>${f.location}</td><td>${f.method}</td><td><span class="pill ${f.status==='Verified'?'':'warn'}">${f.status}</span></td><td><button class="btn ${f.status==='Verified'?'secondary':'primary'}" onclick="farmerDetail('${f.id}')">Review profile →</button></td></tr>`).join('')}</table></section></main>`)}
function farmerDetail(id){if(!guard())return;const f=farmersData().find(x=>x.id===id);if(!f){farmers();return}const ls=listings().filter(x=>x.farmer===f.name),os=orders().filter(x=>x.farmer===f.name);shell(`<main class="wrap">${nav('farmers')}<button class="back" onclick="farmers()">← Back to farmers</button><div style="height:14px"></div><section class="profile-hero"><div><span class="pill ${f.status==='Verified'?'':'warn'}">${f.status.toUpperCase()}</span><h1>${f.name}</h1><p class="muted">${f.farm} • ${f.location}</p></div><div class="profile-actions">${f.status==='Verified'?`<button class="btn danger" onclick="setFarmerStatus('${f.id}','Suspended')">Suspend account</button>`:`<button class="btn primary" onclick="setFarmerStatus('${f.id}','Verified')">✓ Approve farmer</button>`}</div></section><div class="profile-grid"><section class="card"><h2>Identity & verification</h2><div class="detail-row"><span>Farmer ID</span><b>${f.id}</b></div><div class="detail-row"><span>Mobile</span><b>+91 ${f.phone}</b></div><div class="detail-row"><span>Verification method</span><b>${f.method}</b></div><div class="detail-row"><span>Submitted / joined</span><b>${f.joined}</b></div><div class="detail-row"><span>Verification records</span><b>${f.documents}</b></div><div class="notice ok small"><b>Admin review note:</b> In production, this area would display only authorized verification results and permitted documents. Raw Aadhaar numbers should not be exposed here.</div></section><section class="card"><h2>Farm profile</h2><div class="detail-row"><span>Farm / FPO</span><b>${f.farm}</b></div><div class="detail-row"><span>Location</span><b>${f.location}</b></div><div class="detail-row"><span>Primary listed crops</span><b>${f.crops}</b></div><div class="detail-row"><span>Current listings</span><b>${ls.length}</b></div><div class="detail-row"><span>Orders</span><b>${os.length}</b></div></section></div><section class="card wide"><div class="row between"><div><h2>Farmer's marketplace activity</h2><p class="muted small">Review the listings associated with this farmer before approving or suspending the profile.</p></div></div>${ls.length?`<table class="table"><tr><th>Produce</th><th>Qty</th><th>Price</th><th>Status</th></tr>${ls.map(x=>`<tr><td>${x.emoji||'🌾'} ${x.crop}</td><td>${x.qty} kg</td><td>₹${x.price}/kg</td><td><span class="pill ${x.status==='Active'?'':'warn'}">${x.status}</span></td></tr>`).join('')}</table>`:'<p class="muted">No active listings found.</p>'}</section></main>`)}
function setFarmerStatus(id,status){let fs=farmersData();const f=fs.find(x=>x.id===id);if(!f)return;f.status=status;write('kcFarmers',fs);if(status==='Verified')notifyFarmer(f.name,'Profile verified','Your KisanConnect farmer profile has been approved. You can now list produce.','verification');else if(status==='Suspended')notifyFarmer(f.name,'Account suspended','Your marketplace account has been suspended pending review. Please contact support for clarification.','account');farmerDetail(id)}
function notifyFarmer(farmer,title,message,type){const all=read('kcNotifications',[]);all.push({id:'N'+Date.now()+Math.random().toString(16).slice(2),farmer,title,message,type,time:new Date().toLocaleString('en-IN',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}),read:false});write('kcNotifications',all)}
function adminListings(){if(!guard())return;shell(`<main class="wrap">${nav('listings')}<div class="row between"><div><h1>Marketplace Listings</h1><p class="muted">Moderate listings before and after they reach buyers.</p></div><button class="btn secondary" onclick="location.reload()">↻ Refresh</button></div><section class="card wide"><table class="table"><tr><th>Produce</th><th>Farmer</th><th>Qty</th><th>Price</th><th>Status</th><th>Actions</th></tr>${listings().map(x=>`<tr><td>${x.emoji||'🌾'} <b>${x.crop}</b><div class="small muted">${x.variety||''}</div></td><td>${x.farmer}<div class="small muted">${x.location}</div></td><td>${x.qty} kg</td><td>₹${x.price}/kg</td><td><span class="pill ${x.status==='Active'?'':'warn'}">${x.status}</span></td><td><div class="row"><button class="btn secondary" onclick="toggleListing(${x.id})">${x.status==='Active'?'Pause':'Activate'}</button><button class="btn danger" onclick="adminRemove(${x.id})">Remove</button></div></td></tr>`).join('')}</table></section></main>`)}
function toggleListing(id){let a=listings();const x=a.find(v=>v.id===id);if(!x)return;const was=x.status;x.status=x.status==='Active'?'Paused':'Active';write('kcListings',a);if(x.status==='Paused')notifyFarmer(x.farmer,'Listing paused by admin',`Your ${x.crop} listing (${x.qty} kg at ₹${x.price}/kg) has been paused by the KisanConnect admin team. It is no longer visible to buyers until reactivated.`,'listing');else notifyFarmer(x.farmer,'Listing reactivated',`Your ${x.crop} listing has been reactivated and is visible to buyers again.`,'listing');adminListings()}
function adminRemove(id){let a=listings();const x=a.find(v=>v.id===id);if(!x)return;if(confirm(`Remove ${x.crop} listed by ${x.farmer}?`)){write('kcListings',a.filter(v=>v.id!==id));notifyFarmer(x.farmer,'Listing removed by admin',`Your ${x.crop} listing (${x.qty} kg at ₹${x.price}/kg) was removed by the KisanConnect admin team. Please review the listing details or contact support if you believe this was a mistake.`,'listing');adminListings()}}
function adminOrders(){if(!guard())return;const os=orders();shell(`<main class="wrap">${nav('orders')}<div class="row between"><div><h1>Orders & Logistics</h1><p class="muted">Monitor buyer orders and logistics progress.</p></div></div>${os.length?os.map(o=>`<section class="card wide"><div class="row between"><div><span class="pill">${o.status}</span><h2>${o.emoji||'🌾'} ${o.crop} — ${o.qty} kg</h2><p class="small muted">${o.id} • Farmer: ${o.farmer} • Buyer: ${o.buyer||'Buyer'}</p></div><button class="btn primary" onclick="advanceAdmin('${o.id}')">Advance status</button></div><div class="statline"><span>Tracking</span><b>${o.trackingId||'—'}</b></div><div class="statline"><span>Delivery partner</span><b>${o.partner||'Not assigned'}</b></div><div class="statline"><span>Total</span><b>₹${Number(o.total||0).toLocaleString('en-IN')}</b></div></section>`).join(''):`<section class="card empty"><h2>No orders</h2><p class="muted">Place a buyer order on the main website and it will appear here.</p></section>`}</main>`)}
function advanceAdmin(id){let a=orders();const x=a.find(v=>v.id===id);if(!x)return;const stages=['Order placed','Farmer accepted','Pickup scheduled','Picked up','In transit','Delivered'];let i=Math.max(0,Number(x.statusIndex||0));if(i<stages.length-1)i++;x.statusIndex=i;x.status=stages[i];x.events=x.events||[];x.events.push({status:x.status,time:'Admin demo',note:'Status advanced from Admin Panel.'});write('kcOrders',a);adminOrders()}
function recovery(){if(!guard())return;const slow=listings().filter(x=>x.status==='Slow sales'||x.status==='Paused');shell(`<main class="wrap">${nav('recovery')}<h1>Unsold Stock Recovery</h1><p class="muted">Identify produce that may need alternative sales channels.</p><div class="layout2"><section class="card"><h2>At-risk listings</h2>${slow.length?slow.map(x=>`<div class="statline"><span>${x.emoji||'🌾'} ${x.crop} — ${x.qty} kg</span><b>₹${x.price}/kg</b></div>`).join(''):'<p class="muted">No slow-sale listings currently flagged.</p>'}</section><section class="card"><h2>Recovery workflow</h2><div class="timeline"><div class="event"><span class="dot"></span><div><b>1. Match bulk buyers</b><p class="small muted">Check retailers, wholesalers and institutional demand.</p></div></div><div class="event"><span class="dot"></span><div><b>2. Match processors</b><p class="small muted">Look for processors that can accept the produce.</p></div></div><div class="event"><span class="dot"></span><div><b>3. Check procurement eligibility</b><p class="small muted">Government procurement depends on active schemes, crop/state eligibility and agency capacity.</p></div></div></div></section></div></main>`)}
function disputeTone(severity){return severity==='High'?'red':severity==='Medium'?'warn':''}
function setDisputeStatus(id,status){let ds=disputes();const d=ds.find(x=>x.id===id);if(!d)return;d.status=status;d.updated='Admin demo';write('kcDisputes',ds);riskDisputes()}
function riskDisputes(){
  if(!guard())return;
  const ds=disputes(),ls=listings(),fs=farmersData(),os=orders();
  const open=ds.filter(d=>d.status==='Open').length, high=ds.filter(d=>d.severity==='High'&&d.status!=='Resolved').length, paused=ls.filter(x=>x.status==='Paused').length, pending=fs.filter(x=>x.status!=='Verified').length, transit=os.filter(x=>x.status==='In transit').length;
  shell(`<main class="wrap">${nav('risk')}<div class="row between"><div><span class="pill">RISK OPERATIONS</span><h1>⚠️ Risk & Dispute Center</h1><p class="muted">Central review queue for marketplace disputes, suspicious activity and operational risk signals.</p></div><button class="btn secondary" onclick="riskDisputes()">↻ Refresh</button></div>
  <div class="risk-banner"><div><span class="ai-kicker">CONTROL ROOM</span><h2>Protect the marketplace without hiding the evidence.</h2><p>Use documented signals, order records and seller/buyer reports to decide what needs review. Prototype actions only.</p></div><div class="risk-banner-score"><span>OPEN CASES</span><b>${open}</b><small>${high} high-severity</small></div></div>
  <div class="grid risk-metrics" style="margin-top:16px"><div class="card metric-card"><div class="small muted">Open disputes</div><div class="metric">${open}</div></div><div class="card metric-card"><div class="small muted">High-severity cases</div><div class="metric">${high}</div></div><div class="card metric-card"><div class="small muted">Paused listings</div><div class="metric">${paused}</div></div><div class="card metric-card"><div class="small muted">Pending farmer reviews</div><div class="metric">${pending}</div></div></div>
  <div class="layout2"><section class="card"><div class="row between"><div><h2>🚦 Risk signals</h2><p class="small muted">Signals are prompts for human review, not automatic guilt.</p></div><span class="pill">LIVE DEMO</span></div><div class="risk-signal"><span>🚩 Disputes requiring attention</span><b>${open}</b></div><div class="risk-signal"><span>🔴 High-severity unresolved</span><b>${high}</b></div><div class="risk-signal"><span>📋 Listings paused</span><b>${paused}</b></div><div class="risk-signal"><span>👤 Farmer verification pending</span><b>${pending}</b></div><div class="risk-signal"><span>🚚 Orders in transit</span><b>${transit}</b></div></section><section class="card"><h2>🧭 Review playbook</h2><div class="timeline"><div class="event"><span class="dot"></span><div><b>1. Preserve evidence</b><p class="small muted">Keep order, listing, tracking and report details together.</p></div></div><div class="event"><span class="dot"></span><div><b>2. Contact both sides</b><p class="small muted">Separate buyer claims from seller/logistics responses.</p></div></div><div class="event"><span class="dot"></span><div><b>3. Resolve or escalate</b><p class="small muted">Apply the marketplace policy and escalate complex cases.</p></div></div></div></section></div>
  <section class="card wide"><div class="row between"><div><h2>Dispute queue</h2><p class="small muted">Demo queue combining buyer reports and automated risk signals.</p></div><span class="pill">${ds.length} total cases</span></div>${ds.length?`<div class="risk-case-list">${ds.map(d=>`<article class="risk-case"><div class="risk-case-top"><div><span class="pill ${disputeTone(d.severity)}">${d.severity.toUpperCase()}</span><span class="pill case-status">${d.status}</span><h3>${d.id} · ${escRisk(d.type)}</h3><p class="small muted">${escRisk(d.parties)} • ${escRisk(d.order)} • ${escRisk(d.created)}</p></div><div class="risk-case-actions">${d.status!=='Resolved'?`<button class="btn secondary" onclick="setDisputeStatus('${d.id}','Monitoring')">Monitor</button><button class="btn primary" onclick="setDisputeStatus('${d.id}','Resolved')">Resolve</button>`:`<span class="pill">✓ Resolved</span>`}</div></div><p>${escRisk(d.reason)}</p><div class="risk-evidence"><span>Evidence: <b>${escRisk(d.evidence)}</b></span><span>Source: <b>${escRisk(d.source)}</b></span>${d.updated?`<span>Updated: <b>${escRisk(d.updated)}</b></span>`:''}</div></article>`).join('')}`:'<div class="empty"><h2>No disputes</h2><p class="muted">The queue is clear.</p></div>'}</section>
  <section class="card wide"><h2>Risk controls</h2><div class="risk-control-grid"><div><b>Seller controls</b><p class="small muted">Verification, listing moderation, suspension and re-review.</p></div><div><b>Buyer controls</b><p class="small muted">Report issues, preserve order evidence and route disputes.</p></div><div><b>Logistics controls</b><p class="small muted">Track delayed pickups, failed delivery and status anomalies.</p></div><div><b>Data controls</b><p class="small muted">Limit sensitive data exposure and retain only what operations need.</p></div></div></section>
  </main>`)
}
function escRisk(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}

function logout(){sessionStorage.removeItem('kcAdmin');login()}
farmersData();
if(sessionStorage.getItem('kcAdmin')==='1')dashboard();else login();
